import { GoogleGenAI } from "@google/genai";
import { client } from "@gradio/client";

async function scrapeDDGImages(query: string): Promise<string[]> {
  try {
    const res1 = await fetch(`https://duckduckgo.com/?q=${encodeURIComponent(query)}`, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' } });
    const html = await res1.text();
    const vqdMatch = html.match(/vqd=([\w-]+)/);
    if (!vqdMatch) return [];
    const vqd = vqdMatch[1];
    
    const res2 = await fetch(`https://duckduckgo.com/i.js?q=${encodeURIComponent(query)}&o=json&vqd=${vqd}&f=,,,&p=1`, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' } });
    const data = await res2.json();
    if (data.results && data.results.length > 0) {
      return data.results.slice(0, 10).map((r: any) => r.image);
    }
  } catch (err) {
    console.error('DDG Scraper Error:', err);
  }
  return [];
}

export async function generateImage(lastUserMessage: string, apiKey: string): Promise<string> {
  const genAI = new GoogleGenAI({ apiKey });
  
  try {
    // ENGINE A: Try Google Imagen 4 with the user's API Key
    const response = await genAI.models.generateImages({
      model: "imagen-4.0-generate-001",
      prompt: lastUserMessage,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/jpeg"
      }
    });
    if (!response.generatedImages || response.generatedImages.length === 0 || !response.generatedImages[0].image?.imageBytes) {
      throw new Error("No images generated by Imagen 4.");
    }
    const base64Image = response.generatedImages[0].image.imageBytes;
    return `# Image Generation Complete (PRO)\n\nHere is your highly accurate image generated with Google's Imagen 4:\n\n![Generated Image](data:image/jpeg;base64,${base64Image})\n\n*Note: Powered by your Pro API Key.*`;
  } catch (error) {
    console.error("Imagen API Failed, falling back to Hybrid Search:", error);
    // ENGINE B: Hybrid Real-Photo Search + FLUX
    const cleanQuery = lastUserMessage.replace(/^search /i, "").trim();
    
    let finalImageUrl = "";
    let isRealPhoto = false;

    let enhancedPrompt = cleanQuery;

    try {
      // Step 1: Extract Search Term or Intent, and enhance the prompt if it's fictional
      const titleResponse = await genAI.models.generateContent({
        model: "gemini-2.5-flash",
        contents: `Analyze this user request: "${cleanQuery}". 
        If the MAIN subject is a REAL existing PLACE, BUILDING, or UNIVERSITY (like 'Daffodil International University'), you MUST return a DuckDuckGo search query for that place (append 'campus building high quality photo').
        HOWEVER, if the main subject is an IMAGINARY SCENE, ABSTRACT CONCEPT (like AI, Machine Learning), or a SPECIFIC CHARACTER, you MUST translate it to English (if it's in another language) and write a highly detailed, professional, Midjourney-style image generation prompt.
        If writing an enhanced prompt, start your response exactly with: GENERATE_AI:`
      });
      
      let searchTerm = titleResponse.text?.trim() || "GENERATE_AI: " + cleanQuery;
      
      if (searchTerm.startsWith("GENERATE_AI:")) {
        enhancedPrompt = searchTerm.replace("GENERATE_AI:", "").trim();
        searchTerm = "FICTIONAL"; // Marks it as not a real photo
      }
      
      if (searchTerm !== "FICTIONAL") {
        // Step 2: Fetch valid image URLs directly from DuckDuckGo
        const images = await scrapeDDGImages(searchTerm);
        if (images.length > 0) {
          // Always pick the FIRST result to guarantee 100% accuracy. 
          finalImageUrl = images[0];
          isRealPhoto = true;
        }
      }
    } catch (searchError) {
      console.error("Gemini extraction failed (Rate Limit?), using raw query fallback:", searchError);
      
      const isPlace = /university|college|school|hospital|park|city|building/i.test(cleanQuery);
      const isCreative = /create|generate|draw|make|imagine/i.test(cleanQuery);

      if (isCreative && !isPlace) {
        console.log("Fallback: Detected creative intent for non-place, routing to FLUX.");
      } else {
        const cleanedForDDG = cleanQuery.replace(/create|generate|draw|image|photo/gi, "").trim();
        const fallbackImages = await scrapeDDGImages(cleanedForDDG + " campus building high quality photo");
        if (fallbackImages.length > 0) {
          finalImageUrl = fallbackImages[0];
          isRealPhoto = true;
        }
      }
    }

    if (!isRealPhoto) {
      // Use Pollinations AI (FLUX model) as it's reliable and has no ZeroGPU limits
      const encodedQuery = encodeURIComponent(enhancedPrompt);
      const randomSeed = Math.floor(Math.random() * 100000);
      finalImageUrl = `https://image.pollinations.ai/prompt/${encodedQuery}?model=flux&nologo=true&seed=${randomSeed}`;
    }
    
    const statusText = isRealPhoto ? " (Real Photo)" : " (Pro AI Render)";
    
    const professionalNotes = [
      "Crafted with advanced AI precision to match your creative vision.",
      "Generated using state-of-the-art AI rendering technology.",
      "An exclusive AI-generated masterpiece tailored to your prompt.",
      "Brought to life by next-generation generative AI models.",
      "Digitally rendered by our high-performance AI visual engine.",
      "Designed specifically for you using top-tier AI capabilities."
    ];
    const randomNote = professionalNotes[Math.floor(Math.random() * professionalNotes.length)];

    const noteText = isRealPhoto 
      ? "I found the original high-quality photo for you from the web."
      : randomNote;
    
    // Using standard Markdown syntax `![alt](url)` ensures it renders perfectly everywhere.
    return `# 🖼️ Image Result${statusText}\n\nHere is the image you requested:\n\n![Generated Image](${finalImageUrl})\n\n[📥 Click here to Download or View Full Size](${finalImageUrl})\n\n*Note: ${noteText}*`;
  }
}
